hw02_unpack_string - homework_2
AlexandrKusmarov/otus-go-pro pull request #2
Opened 2024-09-05 10:10 UTC by AlexandrKusmarov

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-05 15:28 UTC, vladislavmass requested changes

2024-09-05 15:28 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	for i, r := range input {
В go так лучше не делать. Когда мы итерируемся по строке то r, это руна а i это индекс 1 байта. Это работает для однобайтовых кодировок но создает проблемы с многобайтовыми. Из за этого если мы применим этот метод к слову `да`, то мы получим следующий слайс `"д", "" ,"а", ""`. И тогда если мы попробуем распаковать строку `д2а` на выходе мы получим `да`. Так как удвоим мы пустую строку

2024-09-05 15:28 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	result := make([]string, len(input))
`len(input)` для строки вернет не число букв, а число байт. Тоесть длинна слова `да` будет не 2 а 4

2024-09-05 15:28 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	result := make([]string, len(input))
Подскажите почему решили привести к славу строк, а не к слайду рун. Ведь руны по памяти более оптимальны

2024-09-05 15:28 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		if i == FirstElementOfArray { // Первый элемент массива
Зачем мы делаем эту проверку в цикле? Ведь ситуация когда индекс элемента равен 0 может быть всего 1 раз

2024-09-06 08:31 UTC, AlexandrKusmarov commented on hw02_unpack_string/unpack.go
> +	for i, r := range input {
Действительно с русскими символами возникли проблемы, в дебаге посмотрел. 
Переделал на руны, добавил тест кейсы.

2024-09-06 08:33 UTC, AlexandrKusmarov commented on hw02_unpack_string/unpack.go
> +	result := make([]string, len(input))
Сделал так по незнанию, переделал на руны. Спасибо за ревью)

2024-09-06 08:33 UTC, AlexandrKusmarov commented on hw02_unpack_string/unpack.go
> +		if i == FirstElementOfArray { // Первый элемент массива
Проверку вынес вне цикла. Согласен, в цикле это не нужно делать.

2024-09-09 14:09 UTC, hungry-honeybadger approved these changes

2024-09-09 14:09 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +func splitString(input string) []string {
Возвращать слайс рун было бы все таки лучше. Как минимум руна весит меньше чем строка

2024-09-09 14:09 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +		if err2 != nil { // Если это не цифра и предыдущий цифра - continue.
Тут не нужна err2, можно использовать err.

2024-09-09 14:09 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +			if i == len(splitedStringArr)-1 {
Опять таки код который выполнится максимум один раз за все время работы программы, но проверку это мы будем делать на каждую не цифру

2024-09-09 14:09 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +	if len(splitedStringArr) == 1 { // Если массив состояит только из 1 буквы - пишем
Это никакой-то особенный тест кейс.  Его можно обработать в обычном порядке.

2024-09-12 15:16 UTC, merged