hw04_lru_cache - homework_4
AlexandrKusmarov/otus-go-pro pull request #4
Opened 2024-09-15 16:43 UTC by AlexandrKusmarov

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-15 17:08 UTC, vladislavmass requested changes

2024-09-15 17:08 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	MapKeyCache Key
Структуры менять нельзя

2024-09-15 17:08 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case item == l.head:
Если в листе всего 1 элемент то мы удалим его только из начала,  tail так и будет на него указывать

2024-09-15 17:08 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len < 2 {
Для чего нужно это условие? Выглядит как попытка не перемещать единственный элемент, но это можно сделать более универсально. `l.head==item`

2024-09-21 07:57 UTC, AlexandrKusmarov commented on hw04_lru_cache/list.go
> +	MapKeyCache Key
Поправил

2024-09-21 07:57 UTC, AlexandrKusmarov commented on hw04_lru_cache/list.go
> +	case item == l.head:
Исправлено

2024-09-21 07:57 UTC, AlexandrKusmarov commented on hw04_lru_cache/list.go
> +	if l.len < 2 {
Согласен, поправил

2024-09-21 08:27 UTC, vladislavmass requested changes

2024-09-21 08:27 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +var cache = make(map[*ListItem]Key)
Этого быть не должно. Подумайте  о том, что бы хранить нужный ключ внутри элемента кэша.

2024-09-23 15:28 UTC, AlexandrKusmarov commented on hw04_lru_cache/cache.go
> +var cache = make(map[*ListItem]Key)
Перенес в структуру кэша.
Не понимаю, как еще можно связать элемент с ключом, функции меняют положение элементов в очереди. Теряется привязка с последним элементом кэша без мапы.

2024-09-23 17:26 UTC, vladislavmass requested changes

2024-09-23 17:26 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case item == l.head:
Не вижу тут исправления. Case это как цепочка if else. Также прошу отдельно добавить тест на удаление единственного элемента

2024-09-24 14:27 UTC, AlexandrKusmarov commented on hw04_lru_cache/list.go
> +	case item == l.head:
Убрал if, поправил l.tail. Так же добавил тест на удаление одного элемента

2024-09-24 15:16 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +var cache = make(map[*ListItem]Key)
Так можно просто положить ключ в этот самый связный список

2024-09-26 11:07 UTC, AlexandrKusmarov commented on hw04_lru_cache/cache.go
> +var cache = make(map[*ListItem]Key)
![image](https://github.com/user-attachments/assets/d5579169-d604-4058-9903-aad9fac6fbc2)
Уже делал так

2024-09-26 17:47 UTC, vladislavmass approved these changes

2024-10-02 10:19 UTC, merged