hw05_parallel_execution - HW-5 Implementation
AlexandrKusmarov/otus-go-pro pull request #5
Opened 2024-10-05 12:17 UTC by AlexandrKusmarov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-10-06 04:36 UTC, vladislavmass requested changes

2024-10-06 04:36 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	taskCh := make(chan Task, len(tasks))
Каналы с неизвестным размером очень плохая, так как тасков может быть очень много и буфер может занятье не мало памяти.

2024-10-06 04:36 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	errCh := make(chan error, m)
Непонятно для чего нужен этот канал из которого никто не читает.

2024-10-06 04:36 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +						return
То есть единственный вариант выхода это то, что произошла ошибка.А если у нас есть 1 000 тасков, 6 воркеров и максимум 5 ошибок. Выполнилось первых 5 тасков с ошибками, 1 воркер из 6 закроется( на котором как раз произойдет 5 ошибка), потом ошибок не будет и по итогу оставшиеся 5 воркеров выполнят все таски. Это явно нарушает условие задания

2024-10-06 04:36 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		go func() {
Концепт когда воркер сам управляет своей жизнью не очень правильный, так как требуется синхронизировать работу воркеров и работу рассыльщика тасков. Именно эту проблему все решают делая канал с буфером размером со слайс тасков, что по сути делает его хуже чем слайс тасков + индекс элемента с мьютексом так как канал это и доп память и затраты ресурсов на перемещение тасков в канал. Правильный вариант тут когда работай воркеров управляет тот, кто пишет в канал . Тоесть есть число ошибок меньше максимального пишем в канал, больше или равно закрываем канал. При таком раскладе замечательно заходит не буферезированный канал

2024-10-09 16:42 UTC, AlexandrKusmarov commented on hw05_parallel_execution/run.go
> +	taskCh := make(chan Task, len(tasks))
Исправил

2024-10-09 16:53 UTC, AlexandrKusmarov commented on hw05_parallel_execution/run.go
> +	errCh := make(chan error, m)
Канал используется для остановки горутин по достижению количества ошибок

2024-10-09 16:54 UTC, AlexandrKusmarov commented on hw05_parallel_execution/run.go
> +						return
Изменил логику работы приложения

2024-10-09 16:54 UTC, AlexandrKusmarov commented on hw05_parallel_execution/run.go
> +		go func() {
Учел замечания, логика изменена

2024-10-09 18:56 UTC, vladislavmass approved these changes

2024-10-09 18:56 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +func incrementErrCountAndGet(mu *sync.Mutex, errCount *int) {
Что значит Get в имени этого метода?

2024-10-09 18:56 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +			case <-errCh:
Этот кейс не нужен. Он тут выглядит как нечто, что нужно чисто что бы использовать канал и из за такого подхода мы вынуждены использовать еще и буферезированый канал. Хотя по факту мы можем просто перед отправкой в канал проверить что счетчик ошибок меньше m и это по сути будет то же самое.

2024-10-13 07:23 UTC, merged