Hw07 file copying
AlexandrKusmarov/otus-go-pro pull request #7
Opened 2024-10-20 11:30 UTC by AlexandrKusmarov

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-10-20 12:38 UTC, vladislavmass requested changes
Хорошее начало, но код никак не отрабатывает копирование файлов по типу /dev/urandom. А также если from=to то пользователь потеряет свои данные, чего быть не должно

2024-10-20 12:38 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +func limitCorrector(f *os.File, limit *int64, offset *int64) error {
Подскажите для чего решили сделать этот метод?

2024-10-20 18:21 UTC, AlexandrKusmarov commented on hw07_file_copying/copy.go
> +func limitCorrector(f *os.File, limit *int64, offset *int64) error {
При сравнении текстового файла (из папки testdata) с результатами копирования - количество символов разное на величину \r. Поэтому необходимо добавить к limit и offset количество байт равное найденному количеству \r.
Если можно это сделать библиотечными методами буду рад узнать.

2024-10-20 19:08 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +func limitCorrector(f *os.File, limit *int64, offset *int64) error {
Данный подход в корне не верен. Так как решается проблема которой по сути нет. Скорее всего данное дз делалось на винде, которая отконвертировала файлы в из LF в CRLF и отправила вместе с коммитом на гитхаб. Поэтому необходимо удалить этот метод и вернуть файлы в папке testdata в формат LF

2024-10-20 19:10 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if fromPath == toPath {
Пути 1.txt и ~/tmp/1.txt вполне могут указывать на один и тот же файл. Поэтому сравнивать пути как просто строки не корректно

2024-10-25 16:21 UTC, vladislavmass approved these changes

2024-10-28 07:34 UTC, merged